/**
 * This class is generated by jOOQ
 */
package com.schedushare.core.database.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class Timeblock extends org.jooq.impl.UpdatableTableImpl<com.schedushare.core.database.tables.records.TimeblockRecord> {

	private static final long serialVersionUID = 1827580523;

	/**
	 * The singleton instance of schedushare.timeblock
	 */
	public static final com.schedushare.core.database.tables.Timeblock TIMEBLOCK = new com.schedushare.core.database.tables.Timeblock();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.schedushare.core.database.tables.records.TimeblockRecord> getRecordType() {
		return com.schedushare.core.database.tables.records.TimeblockRecord.class;
	}

	/**
	 * The table column <code>schedushare.timeblock.ID</code>
	 * <p>
	 * This column is part of the table's PRIMARY KEY
	 */
	public final org.jooq.TableField<com.schedushare.core.database.tables.records.TimeblockRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The table column <code>schedushare.timeblock.START_TIME</code>
	 */
	public final org.jooq.TableField<com.schedushare.core.database.tables.records.TimeblockRecord, java.sql.Time> START_TIME = createField("START_TIME", org.jooq.impl.SQLDataType.TIME, this);

	/**
	 * The table column <code>schedushare.timeblock.END_TIME</code>
	 */
	public final org.jooq.TableField<com.schedushare.core.database.tables.records.TimeblockRecord, java.sql.Time> END_TIME = createField("END_TIME", org.jooq.impl.SQLDataType.TIME, this);

	/**
	 * The table column <code>schedushare.timeblock.DAY</code>
	 */
	public final org.jooq.TableField<com.schedushare.core.database.tables.records.TimeblockRecord, com.schedushare.core.database.enums.TimeblockDay> DAY = createField("DAY", org.jooq.util.mysql.MySQLDataType.VARCHAR.asEnumDataType(com.schedushare.core.database.enums.TimeblockDay.class), this);

	/**
	 * The table column <code>schedushare.timeblock.LATITUDE</code>
	 */
	public final org.jooq.TableField<com.schedushare.core.database.tables.records.TimeblockRecord, java.lang.Double> LATITUDE = createField("LATITUDE", org.jooq.util.mysql.MySQLDataType.DOUBLE, this);

	/**
	 * The table column <code>schedushare.timeblock.LONGITUDE</code>
	 */
	public final org.jooq.TableField<com.schedushare.core.database.tables.records.TimeblockRecord, java.lang.Double> LONGITUDE = createField("LONGITUDE", org.jooq.util.mysql.MySQLDataType.DOUBLE, this);

	/**
	 * The table column <code>schedushare.timeblock.NAME</code>
	 */
	public final org.jooq.TableField<com.schedushare.core.database.tables.records.TimeblockRecord, java.lang.String> NAME = createField("NAME", org.jooq.impl.SQLDataType.VARCHAR, this);
	
	/**
	 * The table column <code>schedushare.timeblock.TYPE</code>
	 */
	public final org.jooq.TableField<com.schedushare.core.database.tables.records.TimeblockRecord, java.lang.String> TYPE = createField("TYPE", org.jooq.impl.SQLDataType.VARCHAR, this);

	/**
	 * The table column <code>schedushare.timeblock.SCHEDULE_ID</code>
	 * <p>
	 * This column is part of a FOREIGN KEY: <code><pre>
	 * CONSTRAINT TimeBlockOwner
	 * FOREIGN KEY (SCHEDULE_ID)
	 * REFERENCES schedushare.schedule (ID)
	 * </pre></code>
	 */
	public final org.jooq.TableField<com.schedushare.core.database.tables.records.TimeblockRecord, java.lang.Integer> SCHEDULE_ID = createField("SCHEDULE_ID", org.jooq.impl.SQLDataType.INTEGER, this);

	public Timeblock() {
		super("TIME_BLOCK", com.schedushare.core.database.Schedushare.SCHEDUSHARE);
	}

	public Timeblock(java.lang.String alias) {
		super(alias, com.schedushare.core.database.Schedushare.SCHEDUSHARE, com.schedushare.core.database.tables.Timeblock.TIMEBLOCK);
	}

	@Override
	public org.jooq.UniqueKey<com.schedushare.core.database.tables.records.TimeblockRecord> getMainKey() {
		return com.schedushare.core.database.Keys.KEY_TIMEBLOCK_PRIMARY;
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.UniqueKey<com.schedushare.core.database.tables.records.TimeblockRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.schedushare.core.database.tables.records.TimeblockRecord>>asList(com.schedushare.core.database.Keys.KEY_TIMEBLOCK_PRIMARY);
	}

	@Override
	@SuppressWarnings("unchecked")
	public java.util.List<org.jooq.ForeignKey<com.schedushare.core.database.tables.records.TimeblockRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.schedushare.core.database.tables.records.TimeblockRecord, ?>>asList(com.schedushare.core.database.Keys.TIMEBLOCKOWNER);
	}

	@Override
	public com.schedushare.core.database.tables.Timeblock as(java.lang.String alias) {
		return new com.schedushare.core.database.tables.Timeblock(alias);
	}
}
