/**
 * This class is generated by jOOQ
 */
package com.schedushare.core.database;

import com.schedushare.core.database.tables.Schedule;
import com.schedushare.core.database.tables.Timeblock;
import com.schedushare.core.database.tables.User;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public class Schedushare extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 330327394;

	/**
	 * The singleton instance of schedushare
	 */
	public static final Schedushare SCHEDUSHARE = new Schedushare();

	/**
	 * No further instances allowed
	 */
	private Schedushare() {
		super("schedushare");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			Schedule.SCHEDULE,
			Timeblock.TIMEBLOCK,
			User.USER);
	}
}
