/**
 * This class is generated by jOOQ
 */
package com.schedushare.core.database;

import com.schedushare.core.database.tables.Schedule;
import com.schedushare.core.database.tables.Timeblock;
import com.schedushare.core.database.tables.User;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in schedushare
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public final class Tables {

	/**
	 * The table schedushare.schedule
	 */
	public static final Schedule SCHEDULE = com.schedushare.core.database.tables.Schedule.SCHEDULE;

	/**
	 * The table schedushare.timeblock
	 */
	public static final Timeblock TIMEBLOCK = com.schedushare.core.database.tables.Timeblock.TIMEBLOCK;

	/**
	 * The table schedushare.user
	 */
	public static final User USER = com.schedushare.core.database.tables.User.USER;

	/**
	 * No instances
	 */
	private Tables() {}
}
