/**
 * This class is generated by jOOQ
 */
package com.schedushare.core.database.enums;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = {"http://www.jooq.org", "2.6.0"},
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings("all")
public enum TimeblockDay implements org.jooq.EnumType {
	Monday("Monday"),

	Tuesday("Tuesday"),

	Wednesday("Wednesday"),

	Thursday("Thursday"),

	Friday("Friday"),

	Saturday("Saturday"),

	Sunday("Sunday"),

	;

	private final java.lang.String literal;

	private TimeblockDay(java.lang.String literal) {
		this.literal = literal;
	}

	@Override
	public java.lang.String getName() {
		return "timeblock_DAY";
	}

	@Override
	public java.lang.String getLiteral() {
		return literal;
	}
}
