package com.schedushare.common.domain.dto;

import java.util.Collection;

import com.google.gson.annotations.SerializedName;

/**
 * Schedule {@link RestEntity} passed between client and server as a JSON representation.
 * 
 * Simple user pojo that is structured to be serialized by JOOQ and automatically mapped.
 * Did not like the DTO generated by JOOQ so we chose to make our own.
 */
public class ScheduleEntity extends RestEntity {

	private final Collection<TimeBlockEntity> timeBlocks;
	
	
	public static final String SCHEDULE_NAME = "schedule-name";
	public static final String SCHEDULE_ACTIVE = "active";
	
	@SerializedName(SCHEDULE_NAME)
	private final String scheduleName;
	
	@SerializedName(SCHEDULE_ACTIVE)
	private final Boolean scheduleActive;
	
	/**
	 * Default Constructor.
	 *
	 * @param scheduleName the schedule name
	 * @param scheduleActive the schedule active
	 * @param timeblocks the timeblocks
	 */
	public ScheduleEntity(final String scheduleName, final Boolean scheduleActive, 
			final Collection<TimeBlockEntity> timeblocks) {
		this.scheduleName = scheduleName;
		this.scheduleActive = scheduleActive;
		timeBlocks = timeblocks;
	}
	
	public Collection<TimeBlockEntity> getTimeBlocks() {
		return this.timeBlocks;
	}
	
	public String getScheduleName() {
		return this.scheduleName;
	}
	
	public Boolean isScheduleActive() {
		return this.scheduleActive;
	}
	
	
}
