package com.schedushare.common.domain.dto;

import java.util.Collection;

/**
 * Time blocks {@link RestEntity} passed between client and server as a JSON representation.
 * 
 * Simple user pojo that is structured to be serialized by JOOQ and automatically mapped.
 * Did not like the DTO generated by JOOQ so we chose to make our own.
 */
public class TimeBlocksEntity extends RestEntity {

	private Collection<TimeBlockEntity> timeBlocks;
	
	/**
	 * Constructor.
	 *
	 * @param timeBlocks the time blocks
	 */
	public TimeBlocksEntity(final Collection<TimeBlockEntity> timeBlocks) {
		this.timeBlocks = timeBlocks;
	}
	
	public Collection<TimeBlockEntity> getTimeBlocks() {
		return timeBlocks;
	}
}
