package com.schedushare.common.domain.dto;

import com.google.gson.annotations.SerializedName;

/**
 * Time block {@link RestEntity} passed between client and server as a JSON representation.
 * 
 * Simple user pojo that is structured to be serialized by JOOQ and automatically mapped.
 * Did not like the DTO generated by JOOQ so we chose to make our own.
 */
public class TimeBlockEntity extends RestEntity {

	public static final String START_TIME = "start-time";
	public static final String END_TIME = "end-time";
	public static final String DAY = "day";
	
	@SerializedName(START_TIME)
	private final String startTime;
	
	@SerializedName(END_TIME)
	private final String endTime;
	
	@SerializedName(DAY)
	private final String day;
	
	
	/**
	 * Default Constructor.
	 *
	 * @param START_TIME the start time
	 * @param END_TIME the end time
	 * @param DAY the day
	 */
	public TimeBlockEntity(final String START_TIME, final String END_TIME, final String DAY) {
		this.startTime = START_TIME;
		this.endTime = END_TIME;
		this.day = DAY;
		
	}

	public String getStartTime() {
		return startTime;
	}


	public String getEndTime() {
		return endTime;
	}


	public String getDay() {
		return day;
	}
}
