package com.schedushare.common.domain.dto;

import java.io.Serializable;

import com.google.gson.annotations.SerializedName;

/**
 * User {@link RestEntity} passed between client and server as a JSON representation.
 * 
 * Simple user pojo that is structured to be serialized by JOOQ and automatically mapped.
 * Did not like the DTO generated by JOOQ so we chose to make our own.
 */
public class UserEntity extends RestEntity implements Serializable{
	
	/**
	 * 
	 */
	private static final long serialVersionUID = -5832677761522878554L;

	public static final String AUTH_TOKEN = "auth-token";
	public static final String EMAIL = "email";
	public static final String NAME = "name";
	public static final String USER_ID = "user-id";

	@SerializedName(USER_ID)
	private String userId;
	
	@SerializedName(EMAIL)
	private String email;
	
	@SerializedName(AUTH_TOKEN)
	private String authToken;

	@SerializedName(NAME)
	private String name;
	
	/**
	 * Default constructor.
	 * 
	 * Used by jooq to read from/into database.
	 *
	 * @param ID the id
	 * @param AUTH_TOKEN the auth token
	 * @param Name the name
	 * @param EMAIL the email
	 */
	public UserEntity(final String ID, final String AUTH_TOKEN, final String NAME, 
			final String EMAIL) {
		this.userId = ID;
		this.email = EMAIL;
		this.name = NAME;
		this.authToken = AUTH_TOKEN;
	}

	public String getEmail() {
		return this.email;
	}
	
	public String getAuthToken() {
		return this.authToken;
	}

	public String getName() {
		return this.name;
	}

	public String getUserId() {
		return userId;
	}
}
